apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgCGjReOIRahjOzR6Pc5ElISbA5sz1LHxa7oJA5h62BD7P3AqFaAYf604DPfFRdedgGOflaoZsPmjaxqBKtG+9ziBQO0M188wveH3rYvSlzy52YgQ09/iwYZ7sK4DasGnOvvHduKO3ZXOpsRHrz4pAXSIepgDArvba4UUkjSB0tSlBA8yGzw1K+7x6k0seVD4qzOGHarTo4maMQfIQ4zMDYCx5t/VeM1MQpP9sDzxS9+hoc8igKGkIzNYXZYgn5f6VsI29uuRAbEHVRAU+sAgbDKz9t3DBMdH6c1VLpSiB7OjOahPn4qIe7KVzeBmVyWRq6ERYo9sG0t8vBGi6r9o0lnWmnu9zPnlmxO16tl5pPfpTI+1TQEK6y/xVd+SUR1yCk0A+26T6Fn3FGQcdK3vYSCuAiM24fAoeD1M0Ru9ZCmbyPC6Xfvl8fwaCWdBSO4+pCLJVspkbuX/jd4/RVtE7El0kSrS3RMKeGaJKzGzzre4M9QAvFkmsh+r6J37/lL4GR+RaaRB6aO+BGqxQ3JH5O8//IpKLF2BxFNkJzn8hYK9YzRO/Zc64tEbvJFycBBY0zgP9iXiq4P68maDo4Z9c4z67Cp4J1XAT5+qLXM1wK1/3I1WAgQPJV4uxYvOPSySY+vNNsZipWVT1l2DS0QjgHstfwrJypUsZju8/4tLaf+BPtc5eCeOPOxGf/byaJcHxkpGGeBs7h4OQM=
    user: AgAymUQwDOLGdmRkMS0ZhhMg6YB60cYq4KHYaVBNO8BMIDeMa1OKjM/alb7NlxuwvvUE/mn12ycJmbUFUB/sZRCMKqAe+NSSyYVsYZfhBgNvwPg3HB7pwsAU0iHnIJGgrSQG9nijqK362q6EvYjnVWJOfZrla93EcG6Qz1/VcBuzstPhbNxx30yPsupl9ZoTXfONPEl1VO1WTcBqQNKvL1Vxx5tCROfQyuDN1oKBIVi4EC17a6g1wPoxyFpL/rJsZ7y7rFCj8K0XuQ576kE2GLy+KaGPfNAYMcvy9ZdPb8B5MvxJmbvfTmxSd3Z9Y88crwnSejkcCG3z1KXuR/+S4ShcZvt+n7/OMMihbPWGMQ9c2bSq4FvbAwXoKdkpoKYjMhxGdNd2V2C0vuxkbBowKdqlsB41rLDd7qp/BTPV2ydvTm7UoBLA3VO700Ni5LNX6Ou+veZE57CKIyth8avY4xawRBIJmizuGEn2vHbv+WQHPjl9LW9o89mdpde+KA6Nf9YJ6wH8K5amcroCDUR6CmyoG+8T2itEhjK1cSkL10aqA4a7/6ldrkm9zgrnScykLcwOCIRVSN6XbYG6Yc7uBNddQYErOm3amlyfCubWxMNmUpBlwt8e4emPjxXPBuhEbX7YCfYtIjluk9xEq/CO3LzDPa9ZMnQXmAG64bXmpwGyaR0Q6L+/tbOi2aSYpQC1o7UQdJ/8hA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
